[program:letsens-mqtt-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/dajayape/Documents/work/makerindo/employment/projects/letsens/code/backend/artisan mqtt:subscribe
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=dajayape
numprocs=1
redirect_stderr=true
stdout_logfile=/home/dajayape/Documents/work/makerindo/employment/projects/letsens/code/backend/storage/logs/mqtt-worker.log
stopwaitsecs=3600
